module k_7_tb;
reg a,b,c,d;
wire out;
k_5 uut(.a(a),.b(b),.c(c),.d(d),.out(out));
initial begin
$monitor("a=%b b=%b c=%b d=%d out=%b",a,b,c,d,out);
a=0;b=0;c=0;d=0;#10;
a=0;b=0;c=0;d=1;#10; 
a=0;b=0;c=1;d=0;#10; 
a=0;b=0;c=1;d=1;#10; 
a=0;b=1;c=0;d=0;#10; 
a=0;b=1;c=0;d=1;#10; 
a=0;b=1;c=1;d=0;#10; 
a=0;b=1;c=1;d=1;#10; 
a=1;b=0;c=0;d=0;#10; 
a=1;b=0;c=0;d=1;#10; 
a=1;b=0;c=1;d=0;#10; 
a=1;b=0;c=1;d=1;#10; 
a=1;b=1;c=0;d=0;#10; 
a=1;b=1;c=0;d=1;#10; 
a=1;b=1;c=1;d=0;#10; 
a=1;b=1;c=1;d=1;#10; 
$finish;
end
endmodule
